name: local_assist
description: A helpful local service assist app.
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.1
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  google_sign_in: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
