// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDIAjn33jZ_1X0X-mnIf5vZ-IcMtNs7NU4",
    authDomain: "local-assist-4bbd3.firebaseapp.com",
    projectId: "local-assist-4bbd3",
    storageBucket: "local-assist-4bbd3.appspot.com",
    messagingSenderId: "559664526518",
    appId: "1:559664526518:web:abc123def456789012345678",
    measurementId: "G-XXXXXXXXXX",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDIAjn33jZ_1X0X-mnIf5vZ-IcMtNs7NU4",
    appId: "1:559664526518:android:dea75927e5b2ac3285e217",
    messagingSenderId: "559664526518",
    projectId: "local-assist-4bbd3",
    storageBucket: "local-assist-4bbd3.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDIAjn33jZ_1X0X-mnIf5vZ-IcMtNs7NU4",
    appId: "1:559664526518:ios:dea75927e5b2ac3285e217",
    messagingSenderId: "559664526518",
    projectId: "local-assist-4bbd3",
    storageBucket: "local-assist-4bbd3.appspot.com",
    androidClientId: "559664526518-abcdef123456.apps.googleusercontent.com",
    iosClientId: "559664526518-ghijkl789012.apps.googleusercontent.com",
    iosBundleId: "com.example.localassist",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDIAjn33jZ_1X0X-mnIf5vZ-IcMtNs7NU4",
    appId: "1:559664526518:macos:dea75927e5b2ac3285e217",
    messagingSenderId: "559664526518",
    projectId: "local-assist-4bbd3",
    storageBucket: "local-assist-4bbd3.appspot.com",
    androidClientId: "559664526518-abcdef123456.apps.googleusercontent.com",
    iosClientId: "559664526518-ghijkl789012.apps.googleusercontent.com",
    iosBundleId: "com.example.localassist",
  );
}